apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - webserver-deployment.yaml
  - webserver-service.yaml
images:
  - name: nginx
    newName: 285078527605.dkr.ecr.eu-west-1.amazonaws.com/webserver # {"$imagepolicy": "flux-system:gitops-demo:name"}
    newTag: demo-7d83004-1625029186 # {"$imagepolicy": "flux-system:gitops-demo:tag"}
