apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - webserver-deployment.yaml
  - webserver-service.yaml
images:
  - name: nginx
    newName: 974362571593.dkr.ecr.us-west-1.amazonaws.com/webserver # {"$imagepolicy": "flux-system:gitops-demo:name"}
    newTag: demo-3755bde-1624809421 # {"$imagepolicy": "flux-system:gitops-demo:tag"}
